Repository SeongsangCHO/wanted-preonboarding-subject-3, pull requests merged in 2021-08, with the labels that each got.

#13 로그인 페이지 마크업 및 Input 컴포넌트 머지
  src/Assets/svg/eye_closed.svg
  src/Assets/svg/mail.svg
  src/Components/common/Input.js
  src/Components/common/Radio.js
  src/Pages/Login.js
  src/Styles/Theme.js
Labels: enhancement, style, 로그인/회원가입

#14 헤더 컴포넌트 마크업, 스타일링 머지
  src/App.js
  src/Components/common/Header.js
  src/Components/common/Header/Header.js
  src/Components/common/Header/LoginButton.js
  src/Components/common/Header/LogoutButton.js
  src/Components/common/Header/UserButton.js
  src/Routes.js
  src/assets/logo.png
  src/assets/profile.png
Labels: enhancement, style, 로그인/회원가입

#15 회원가입 페이지 마크업 및 스타일링 머지
  src/Pages/SignUp.js
  src/assets/svg/check.svg
Labels: enhancement, style, 로그인/회원가입

#18 관리자 페이지 권한 별 네비게이션 바 마크업 및 스타일링
  src/Components/common/NavBar.js
  src/Pages/Admin.js
Labels: style, 권한설정, 로그인/회원가입

#20 로그인/회원가입 페이지, 공통 컴포넌트 마크업 및 스타일링
  public/index.html
  src/App.js
  src/Assets/img/logo.png
  src/Assets/img/profile.png
  src/Assets/svg/calendar.svg
  src/Assets/svg/card.svg
  src/Assets/svg/eye_closed.svg
  src/Assets/svg/eye_opened.svg
  src/Assets/svg/mail.svg
  src/Assets/svg/map.svg
  src/Assets/svg/person.svg
  src/Components/common/Button.js
  src/Components/common/Header.js
  src/Components/common/Header/Header.js
  src/Components/common/Header/LoginButton.js
  src/Components/common/Header/LogoutButton.js
  src/Components/common/Header/UserButton.js
  src/Components/common/Input.js
  src/Components/common/Modal/Modal.js
  src/Components/common/Modal/ModalAddress.js
  src/Components/common/Modal/ModalContents.js
  src/Components/common/Modal/ModalCredit.js
  src/Components/common/Modal/ModalPortal.js
  src/Components/common/Modal/SignupModal.js
  src/Components/common/NavBar.js
  src/Components/common/Radio.js
  src/Pages/Admin.js
  src/Pages/Login.js
  src/Pages/SignUp.js
  src/Routes.js
  src/Styles/GlobalStyles.js
  src/Styles/Theme.js
  src/assets/svg/check.svg
Labels: enhancement, style, 관리자, 로그인/회원가입

#21 Feature/adminPage 마크업, 검색 & 필터 기능
  .env
  src/App.js
  src/App.test.js
  src/Components/Admin/AuthFilter/AuthFilter.js
  src/Components/Admin/Pagination/Pagination.js
  src/Components/Admin/SearchBar/SearchBar.js
  src/Components/Admin/UserDataTable/UserDataTable.js
  src/Pages/Admin.js
  src/Styles/GlobalStyles.js
  src/Utils/MockData.js
Labels: enhancement, style, 관리자

#22 Feature/admin 마크업, 검색 & 필터 기능
  .env
  jsconfig.json
  src/App.js
  src/App.test.js
  src/Components/Admin/AuthFilter/AuthFilter.js
  src/Components/Admin/CreateAccount/CreateAccount.js
  src/Components/Admin/Pagination/Pagination.js
  src/Components/Admin/SearchBar/SearchBar.js
  src/Components/Admin/UserDataTable/UserDataTable.js
  src/Pages/Admin.js
  src/Pages/index.js
  src/Routes.js
  src/Styles/GlobalStyles.js
  src/Utils/MockData.js
  src/Utils/Storage.js
  src/Utils/auth.js
  src/Utils/constants.js
  src/index.js
  yarn.lock
Labels: enhancement, style, 관리자

#25 Bug/test 경로문제 fix
  .env
  jsconfig.json
  src/App.js
  src/Pages/Admin.js
  src/Routes.js
  src/Styles/GlobalStyles.js
Labels: bug

#31 어드민 페이지 개인 권한 수정 기능 추가
  src/Components/Admin/AuthFilter/AuthFilter.js
  src/Components/Admin/Pagination/Pagination.js
  src/Components/Admin/UserDataTable/AuthSelector.js
  src/Components/Admin/UserDataTable/UserDataTable.js
  src/Pages/Admin.js
  src/Utils/MockData.js
  src/Utils/constants.js
Labels: enhancement

#33 Feature/admin pagination
  src/Components/Admin/Pagination/Pagination.js
  src/Utils/MockData.js
  src/Utils/constants.js
Labels: enhancement, 관리자

#37 로그인, 회원가입 페이지 유효성 검사 기능 구현
  src/Pages/Login.js
  src/Pages/SignUp.js
  src/Utils/validator.js
Labels: enhancement, 로그인/회원가입

#40 [#4] feat : 페이지네이션 버튼 출력 기능 수정
  src/Components/Admin/Pagination/Pagination.js
Labels: enhancement

#42 Feature/admin style
  src/Components/Admin/UserDataTable/UserDataTable.js
  src/Pages/Admin.js
Labels: enhancement, style, 관리자

#41 엔트리, 로그인, 회원가입 페이지 및 공통 컴포넌트 작업 merge
  package-lock.json
  package.json
  public/index.html
  src/Assets/img/main.png
  src/Components/common/Header/Header.js
  src/Components/common/Header/LogoutButton.js
  src/Components/common/Input.js
  src/Components/common/Modal/AddressModal.js
  src/Components/common/Modal/CreditModal.js
  src/Components/common/Modal/Modal.js
  src/Components/common/Modal/ModalAddress.js
  src/Components/common/Modal/ModalContents.js
  src/Components/common/Modal/ModalCredit.js
  src/Components/common/Modal/ModalPortal.js
  src/Components/common/Modal/SignupModal.js
  src/Components/common/NavBar.js
  src/Components/common/Radio.js
  src/Pages/Login.js
  src/Pages/Main.js
  src/Pages/SignUp.js
  src/Styles/Mixin.js
  src/Utils/Storage.js
  src/Utils/bcrypt.js
  src/Utils/constants.js
  src/Utils/customDesignModal.js
  src/Utils/validator.js
  src/index.js
Labels: enhancement, style, 로그인/회원가입

#39 Feature : admin create user v2
  src/Components/Admin/CreateAccount/CreateAccount.js
  src/Components/common/Modal/Modal.js
  src/Components/common/Modal/ModalContents.js
  src/Pages/Admin.js
  src/Utils/constants.js
Labels: enhancement, style, 관리자

#43 Feature/admin
  jsconfig.json
  src/App.js
  src/Components/Admin/AuthFilter/AuthFilter.js
  src/Components/Admin/CreateAccount/CreateAccount.js
  src/Components/Admin/Pagination/Pagination.js
  src/Components/Admin/SearchBar/SearchBar.js
  src/Components/Admin/UserDataTable/AuthSelector.js
  src/Components/Admin/UserDataTable/UserDataTable.js
  src/Components/Section/Section.js
  src/Components/common/NavBar.js
  src/Pages/Admin.js
  src/Pages/FindTeacher.js
  src/Pages/Kids.js
  src/Pages/Main.js
  src/Pages/MatchUp.js
  src/Pages/Students.js
  src/Pages/index.js
  src/Routes.js
  src/Utils/MockData.js
  src/Utils/Storage.js
  src/Utils/auth.js
  src/Utils/constants.js
  src/index.js
Labels: enhancement, 관리자

#45 Release
  package-lock.json
  src/App.js
  src/Components/Admin/CreateAccount/CreateAccount.js
  src/Components/Admin/UserDataTable/AuthSelector.js
  src/Components/Admin/UserDataTable/UserDataTable.js
  src/Components/common/Button.js
  src/Components/common/Header/Header.js
  src/Components/common/Header/LogoutButton.js
  src/Components/common/Header/UserButton.js
  src/Components/common/Input.js
  src/Components/common/MessageBox.js
  src/Components/common/Modal/CreditModal.js
  src/Components/common/Modal/SignupModal.js
  src/Components/common/NavBar.js
  src/Components/common/Radio.js
  src/Pages/Admin.js
  src/Pages/Login.js
  src/Pages/Main.js
  src/Pages/SignUp.js
  src/Routes.js
  src/Utils/MockData.js
  src/Utils/Storage.js
  src/Utils/auth.js
  src/Utils/constants.js
  src/Utils/customDesignModal.js
  src/Utils/validator.js
  yarn.lock
Labels: enhancement

#48 chore : 검색어 초기화, 엔터시 검색 기능 추가
  src/Components/Admin/SearchBar/SearchBar.js
Labels: enhancement

#49 chore : modal-portal root element 변경
  public/index.html
  src/Components/common/Modal/Modal.js
Labels: refactor
